name: build-wheels-win64

on:
  push:
    branches:
      - wheel
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: build-wheels-win64-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels_win64:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BEFORE_BUILD: "pip install -U cmake numpy"
          CIBW_SKIP: "cp311-* cp312-* *-win32 pp*"
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

          ls -lh ./wheelhouse/*.whl

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel twine setuptools

          twine upload ./wheelhouse/*.whl
